### ISSUE TITLE
Rotation is reset --> Every player can do another action.

### ISSUE THREAD

**Issue by joelhube** [sopra-fs24-group-03/sopra-fs24-group-03-server#133]

**Comment by Colbae** [comment]
This task was already implemented in the task #117 as the updateOrder method. See commit: [bb0cf52](https://github.com/sopra-fs24-group-03/sopra-fs24-group-03-server/commit/bb0cf522e923708ff29f9382a6409c4c59892951)

**Comment by Colbae** [comment]
See also commit: [ec2b5f4](https://github.com/sopra-fs24-group-03/sopra-fs24-group-03-server/commit/ec2b5f45c348748d501f8f733801674410c81307)
